// CUSTOMER

export const GET_CUSTOMER = "GET_CUSTOMER";
export const GET_CUSTOMERBYID = "GET_CUSTOMERBYID";

// DEPARTMENT
export const GET_DEPARTMENT = "GET_DEPARTMENT";
export const GET_DEPARTMENT_BY_ID = "GET_DEPARTMENT_BY_ID"

//EMPLOYEE
export const GET_EMPLOYEE = "GET_EMPLOYEE";

