// CUSTOMER

export const GET_CUSTOMER = "GET_CUSTOMER";
export const GET_CUSTOMER_BY_ID = "GET_CUSTOMER_BY_ID";

// DEPARTMENT
export const GET_DEPARTMENT = "GET_DEPARTMENT";
export const GET_DEPARTMENT_BY_ID = "GET_DEPARTMENT_BY_ID"

//EMPLOYEE
export const GET_EMPLOYEE = "GET_EMPLOYEE";
export const GET_EMPLOYEE_BY_ID = "GET_EMPLOYEE_BY_ID"

// TICKET

export const GET_TICKET = 'GET_TICKET'
export const GET_TICKET_BY_ID = 'GET_TICKET_BY_ID'